export const arrFooter = [
  {
    section: "Categories",
    links: [
      "Graphics & Design",
      "Digital Marketing",
      "Writing & Translation",
      "Video & Animation",
      "Music & Audio",
      "Programming & Tech",
      "AI Services",
      "Consulting",
      "Data",
      "Business",
      "Personal Growth & Hobbies",
      "Photography",
      "Finance",
      "End-to-End Projects",
      "Service Catalog",
    ],
  },
  {
    section: "For Clients",
    links: [
      "How Fiverr Works",
      "Customer Success Stories",
      "Trust & Safety",
      "Quality Guide",
      "Fiverr Learn",
      "Fiverr Guides",
      "Fiverr Answers",
    ],
  },
  {
    section: "For Freelancers",
    links: [
      "Become a Fiverr Freelancer",
      "Become an Agency",
      "Kickstart",
      "Community Hub",
      "Forum",
      "Events",
    ],
  },
  {
    section: "Business Solutions",
    links: [
      "Fiverr Pro",
      "Project Management Service",
      "ClearVoice",
      "Working Not Working",
      "AutoDS",
      "Fiverr Logo Maker",
      "Contact Sales",
    ],
  },
  {
    section: "Company",
    links: [
      "About Fiverr",
      "Help & Support",
      "Social Impact",
      "Careers",
      "Terms of Service",
      "Privacy Policy",
      "Partnerships",
      "Creator Network",
      "Affiliates",
      "Invite a Friend",
      "Press & News",
      "Investor Relations",
    ],
  },
];
